train_data_path: data/processed/train.txt
model_save_path: models/gpt_model.pt
vocab_size: 30522         # Optional (used in tokenizer)
block_size: 128
batch_size: 16
num_epochs: 3
learning_rate: 5e-4